local gears = require('gears');
local awful = require('awful');
local beautiful = require('beautiful');
local dpi = beautiful.xresources.apply_dpi
local xrdb = beautiful.xresources.get_current_theme();

local config = {
  global = {
    m = dpi(10),
    r = dpi(7),
    o = dpi(0.35),
    slider = dpi(30),
    user = gears.filesystem.get_configuration_dir()..'/user.png',
  },
  colors = {
    b = '#1f2026',
    t = '#00000000',
    w = '#fefefe',
    f = '#5a666d96',
    xf = xrdb.foreground,
    xb = xrdb.background,
    x0 = xrdb.color0,
    x1 = xrdb.color1,
    x2 = xrdb.color2,
    x3 = xrdb.color3,
    x4 = xrdb.color4,
    x5 = xrdb.color5,
    x6 = xrdb.color6,
    x7 = xrdb.color7,
    x8 = xrdb.color8,
    x9 = xrdb.color9,
    x10 = xrdb.color10,
    x11 = xrdb.color11,
    x12 = xrdb.color12,
    x13 = xrdb.color13,
    x14 = xrdb.color14,
    x15 = xrdb.color15,
  },
  fonts = {
    is = "Material Design Icons Desktop 12",
    im = "Material Design Icons Desktop 14",
    il = "Material Design Icons Desktop 20",
    ixxl = "Material Design Icons Desktop 100",
    ts = "Cantarell Regular 10",
    tm = "Cantarell Regular 11",
    tl = "Cantarell Regular 13",
    tsl = "Cantarell Light 10",
    tml = "Cantarell Light 11",
    tll = "Cantarell Light 13",
    tsb = "Cantarell Extra Bold 10",
    tmb = "Cantarell Extra Bold 12",
    tlb = "Cantarell Extra Bold 13",
    txlb = "Cantarell Extra Bold 15",
    mlb = "Operator Mono Lig Bold 12",
    mll = "Operator Mono Lig Light 12",
    m = "Operator Mono Lig",
    d = "Cantarell Bold ",
    dl = "Cantarell Light ",
    t = "Cantarell Bold ",
    i = "Material Design Icons Desktop ",
  },
  powermenu = {
    w = dpi(500),
    h = dpi(330),
    hh = dpi(230),
    a = dpi(100),
  },
  topbar = {
    h = dpi(30),
    w = dpi(30),
    dw = dpi(135),
    utilities = {
      wifi = false,
      bt = true,
      lan = true,
      vol = true,
      bat = false,
      pac = true,
      mem = true,
      note = true,
      bat = false,
    },
  },
  tagswitcher = {
    h = dpi(120),
  },
  hub = {
    i = dpi(40),
    w = dpi(800),
    h = dpi(600),
    nw = dpi(260),
  },
  icons = {
    arch = '󰣇',
    power = '󰐥',
    date = '󰸘',
    time = '󰅐',
    vol_mute = '󰝟',
    vol_1 = '󰕿',
    vol_2 = '󰖀',
    vol_3 = '󰕾',
    wifi = '󰖩',
    wifix = '󰖪',
    bt = '󰂯',
    btx = '󰂲',
    pac = '󰏗',
    mem = '󰍛',
    lan = '󰲝',
    lanx = '󰲜',
    note = '󰀠',
    web = '󰖟',
    system = '󰄨',
    display = '󰇄',
    media = '󰝚',
    theme = '󰸌',
    down = '󰳜',
    close = '󰅖',
    clear = '󰎟',
    lock = '󰍁',
    unlock = '󰍀',
    play = '󰐌',
    pause = '󰏥',
    next = '󰒭',
    prev = '󰒮',
    spot = '󰓇',
    restart = '󰜉',
    logout = '󰗽',
    suspend = '󰤄',
    bat10 = '󰁺',
    bat20 = '󰁻',
    bat30 = '󰁼',
    bat40 = '󰁽',
    bat50 = '󰁾',
    bat60 = '󰁿',
    bat70 = '󰂀',
    bat80 = '󰂁',
    bat90 = '󰂂',
    bat = '󰁹',
  },
  commands = {
    getbrightness = gears.filesystem.get_configuration_dir()..'scripts/getbrightness.sh',
    setbrightness = gears.filesystem.get_configuration_dir()..'scripts/setbrightness.sh',
    art = gears.filesystem.get_configuration_dir()..'scripts/albumart.sh',
    getwall = gears.filesystem.get_configuration_dir()..'scripts/wall.sh',
    resize = gears.filesystem.get_configuration_dir()..'scripts/resize.sh',
    cpucmd = gears.filesystem.get_configuration_dir()..'scripts/cpu.sh',
    ramcmd = gears.filesystem.get_configuration_dir()..'scripts/ram.sh',
    diskcmd = gears.filesystem.get_configuration_dir()..'scripts/disk.sh',
    wifiup = gears.filesystem.get_configuration_dir()..'scripts/wifiup.sh',
    lanup = gears.filesystem.get_configuration_dir()..'scripts/lanup.sh',
    btup = gears.filesystem.get_configuration_dir()..'scripts/btup.sh',
    btdevices = gears.filesystem.get_configuration_dir()..'scripts/btdevices.sh',
    btdevice = gears.filesystem.get_configuration_dir()..'scripts/btdevice.sh',
    spotify_state = gears.filesystem.get_configuration_dir()..'scripts/spotify.sh',
    spotify_play = gears.filesystem.get_configuration_dir()..'scripts/spotify.sh recommend --artist "Iron Maiden"',
    kill_spotify = 'bash -c "killall spotifyd && notify-send \'Killed spotifyd.\'"',
    idle = 'bash -c "xidlehook --not-when-audio --timer 500 \'echo lock\' \'\' --timer 9000 \'echo suspend\' \'\'"',
    proccmd = 'bash -c "ps -eo comm,%mem,%cpu --sort=-%cpu,-%mem | head -n 6 | xargs"',
    synccmd = 'bash -c "yay -Syy"',
    updatescmd = 'bash -c "yay -Sup | wc -l"',
    ismuted = 'bash -c "pamixer --get-mute | diff <(echo \"true\") -"',
    vol = 'bash -c "pamixer --get-volume"',
    volup = 'pamixer -i 3',
    voldown = 'pamixer -d 3',
    setvol = 'pamixer --set-volume',
    mute = 'pamixer -t',
    ssid = 'bash -c "iwgetid -r"',
    setwall = 'nitrogen',
    browser = "brave",
    editor = "nvim",
    terminal = "alacritty",
    files = "nautilus",
    spotify = "spotify",
    nvidia = "nvidia-settings",
    rofi = "rofi -show drun -dpi 0 -theme global",
    rofi2 = "rofi -show drun -dpi 0 -theme launcher",
    software = "pamac-manager",
    pause = "playerctl --player=nuclear,%any play-pause",
    play = "playerctl --player=nuclear,%any play-pause",
    next = "playerctl next",
    prev = "playerctl previous",
    artist = gears.filesystem.get_configuration_dir()..'scripts/spotify.sh'..' artist',
    song = gears.filesystem.get_configuration_dir()..'scripts/spotify.sh'..' song',
    isplaying = 'spt playback -s 2>&1 | diff <(echo \"Error: no context available\") -',
    suspend = "systemctl suspend",
    restart = "systemctl reboot",
    shutdown = "systemctl poweroff",
    scrot = "flameshot gui",
    scrotclip = "flameshot gui",
    scrotclipsave = "flameshot gui",
    audiosrc = "pamixer --list-sinks | awk -F\\\" '{print $6}'",
    batcmd = 'bash -c "acpi -V | grep -m 1 \'Battery 1\' | awk -F, \'{print $2}\' | sed \'s/%//\'"',
    dispsecondary = gears.filesystem.get_configuration_dir()..'scripts/dpi.sh'..' 108 150 0',
    dispfull = 'xrandr --output DisplayPort-1 --mode 3440x1440 && xrandr --output HDMI-A-2 --mode 3840x2160 --right-of DisplayPort-1',
    dispidle = gears.filesystem.get_configuration_dir()..'scripts/dpi.sh'..' 150 108 1',
    switch_inputs = gears.filesystem.get_configuration_dir()..'scripts/hotplug_wrapper.sh'..' add',
  },
  notifications = {
    w = dpi(200),
  },
  display = {
    sw = dpi(120),
  },
  media = {
    nowplaying = nil,
  }
};

awful.spawn.easy_async_with_shell('which wezterm', function(o,e,r,c)
  if c == 0 then
    config.commands.terminal = 'wezterm'
  else
    config.commands.terminal = 'alacritty'
  end
end);

return config;
